#!/usr/bin/env python3

import json
import argparse
import time
import os


def parse_arguments():
    parser = argparse.ArgumentParser(description='Implementation of a universal Turing Machine.')
    parser.add_argument('-b', '--initial', type=str, action="store", default="q0", help='Initial state to begin')
    parser.add_argument('-r', '--render', action="store_true", default=False, help='Render turing machine')
    required_arguments = parser.add_argument_group('required arguments')
    required_arguments.add_argument('-i', '--instructions', type=str, action="store", default=False, required=True, help='Instructions, as JSON file')
    required_arguments.add_argument('-t', '--input', type=str, action="store", default=False, required=True, help='Input tape')
    required_arguments.add_argument('-e', '--end', type=str, action="store", default=False, required=True, help='End state')
    return parser.parse_args()


class TuringMachine(object):
    def __init__(self, instructions, tape, start_state, end_state, render):
        self.instructions = instructions
        self.tape = list(tape)
        self.state = start_state
        self.end_state = end_state
        self.render = render
        self.validate_instruction()

    def run(self):
        counter = 0
        index = 0
        self.render_screen(index, counter)
        while self.state != self.end_state:
            counter += 1
            cell = self.tape[index] if index < len(self.tape) else "B"
            if index >= len(self.tape):
                self.tape.append("B")
            self.tape[index] = self.instructions[self.state][cell]["write"]
            index += self.instructions[self.state][cell]["move"]
            self.state = self.instructions[self.state][cell]["nextState"]
            self.render_screen(index, counter)
        return self.tape_as_string()

    def render_screen(self, index, counter):
        if self.render:
            os.system('clear')
            padding = 15 - index
            print("INFO: Count [ %s ] - State [ %s ] - Index [ %s ]\n" % (str(counter).rjust(5), str(self.state).rjust(3), str(index)))
            print(30 * ' ' + '▼')
            self.print_with_pipes(padding*' ' + self.tape_as_string() + (15-(len(self.tape)-(index+1)))*' ')
            print(30 * ' ' + '▲')
            time.sleep(.4)

    @staticmethod
    def print_with_pipes(string):
        print("|".join(string[i:i+1] for i in range(0, len(string))))

    def validate_instruction(self):
        for instruction in self.instructions:
            for case in self.instructions[instruction]:
                state_to_check = self.instructions[instruction][case]['nextState']
                if state_to_check not in self.instructions and state_to_check != self.end_state:
                    raise Exception("Invalid configuration, missing states")

    def tape_as_string(self):
        return str.join('', self.tape)


def main():
    args = parse_arguments()
    try:
        instructions = json.loads(open(args.instructions).read())
        print("Input: {} \nOutput: {}".format(args.input, TuringMachine(instructions, args.input, args.initial, args.end, args.render).run()))
    except Exception as e:
        print("Looks like something went wrong! - %s" % e)


if __name__ == '__main__':
    main()
